# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: iOS Build with Xcode

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Select Xcode version (fallback to latest)
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Build App
      run: |
        xcodebuild -scheme AfricaAnimal \
                   -destination 'platform=iOS Simulator,name=iPhone 15' \
                   clean build

    - name: Run Unit Tests
      run: |
        xcodebuild test -scheme AfricaAnimal \
                        -destination 'platform=iOS Simulator,name=iPhone 15'
